### ISSUE TITLE
Suggestion - moznost keywordu na porizeni screenshotu aktivniho okna

### ISSUE THREAD

**Issue by ghost** [ohomola/gears#3]
Slo by udelat keyword na tipnuti aktivniho okna ? Soubor by se ukladal treba v .jpg > vytvoril by se folder kde by se tento output ukladal pod nejakym ID testu, nejspis datum a cas behu testu.

Diky :)

**Comment by petrahom** [comment]
Tahle featura je jiz v planu. Spolu s automatickym ukladanim screenshotu pri vyskytu Erroru.
